# Generated by Django 3.1.2 on 2021-02-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20210106_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='batman.png', upload_to='perfil-edit'),
        ),
    ]
